server:
  port: 8101
  
spring:
  applicatioin:
    name: app-service
  redis:
    host: localhost
    port: 6379
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/, http://eureka-peer2:8762/eureka/, http://eureka-peer3:8763/eureka/