server:
  port: 8080
  
spring:
  applicatioin:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: ui-route
        uri: lb://ui-service
        predicates:
        - Path=/ui/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/, http://eureka-peer2:8762/eureka/, http://eureka-peer3:8763/eureka/
      